# Generated by Django 4.1.3 on 2023-01-09 15:32

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=150)),
                ('access_token', models.TextField()),
                ('refresh_token', models.CharField(max_length=200)),
                ('active', models.BooleanField()),
                ('scope', models.TextField()),
                ('issued_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('expires_in', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=50, unique=True)),
                ('client_secret', models.TextField()),
                ('name', models.CharField(max_length=50, unique=True)),
                ('response_type', models.CharField(max_length=50)),
                ('scope', models.TextField()),
                ('allowed_cors_origins', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None), size=None)),
                ('grant_type', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None), size=None)),
                ('redirect_uris', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None), size=None)),
                ('date_created', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
        migrations.CreateModel(
            name='WellKnownConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.URLField()),
                ('jwks_uri', models.URLField()),
                ('registration_endpoint', models.URLField()),
                ('authorization_endpoint', models.URLField()),
                ('token_endpoint', models.URLField()),
                ('introspection_endpoint', models.URLField()),
                ('revocation_endpoint', models.URLField()),
                ('userinfo_endpoint', models.URLField()),
                ('claims_parameter_supported', models.BooleanField(default=False)),
                ('request_parameter_supported', models.BooleanField(default=False)),
                ('request_uri_parameter_supported', models.BooleanField(default=False)),
                ('grant_types_supported', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), size=None), size=None)),
                ('scopes_supported', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None), size=None)),
                ('token_endpoint_auth_methods_supported', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None), size=None)),
                ('response_types_supported', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None), size=None)),
                ('token_endpoint_auth_signing_alg_values_supported', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None), size=None)),
                ('claims_supported', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorizationGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('revoked', models.BooleanField(default=False)),
                ('response_type', models.CharField(max_length=50)),
                ('redirect_uri', models.TextField()),
                ('scope', models.TextField()),
                ('grant_type', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None), size=None)),
                ('issued_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('expires_in', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
    ]
