version: '3'
services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: numo
      POSTGRES_DB: id-server
      POSTGRES_PASSWORD: Numonde@1
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/posgresql/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - database
volumes:
  pgdata: